# Generated by Django 5.0 on 2024-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_account_id_alter_useraccount_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='createdByUserId',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='deletedByUserId',
            field=models.BigIntegerField(null=True),
        ),
    ]
