# Generated by Django 5.0 on 2024-03-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accounttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account_type', to='account.accounttype'),
            preserve_default=False,
        ),
    ]
