# Generated by Django 5.0 on 2024-02-11 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_group_parent',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('deleted_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_product_created_by', to=settings.AUTH_USER_MODEL)),
                ('deleted_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_product_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_product_parent_product', to='product.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='group_product_product', to='product.product')),
                ('updated_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_product_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
