# Generated by Django 5.0 on 2024-02-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_is_group_parent_groupproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_group_parent',
            field=models.BooleanField(default=False),
        ),
    ]
