# Generated by Django 5.0 on 2024-02-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_groupproduct_id_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='quantity',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='stocks',
            field=models.PositiveBigIntegerField(),
        ),
    ]
