# Generated by Django 5.0 on 2024-02-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_groupproduct_quantity_alter_product_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
