# Generated by Django 5.0 on 2024-02-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0003_productclassification_created_by_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productclassification',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
