# Generated by Django 5.0 on 2024-02-16 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('product', '0003_alter_product_is_group_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='discounted_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_product', to='product.product'),
        ),
    ]
