# Generated by Django 5.0 on 2024-02-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_discounted_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderdiscount',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
