# Generated by Django 5.0 on 2024-02-16 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='amount',
        ),
    ]
