# Generated by Django 5.0 on 2024-02-16 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0002_remove_paymentmethod_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='refference',
        ),
    ]
