# Generated by Django 5.0 on 2024-02-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0003_remove_paymentmethod_refference'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='account_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
