# Generated by Django 5.0 on 2024-02-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_method', '0005_alter_paymentmethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
