# Generated by Django 5.0 on 2024-01-15 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('user', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='account.account'),
        ),
        migrations.AddField(
            model_name='user',
            name='contactNumber',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
