# Generated by Django 5.0 on 2024-01-15 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_account_remove_user_contactnumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
