# Generated by Django 5.0 on 2024-01-18 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_useraccount'),
        ('order', '0002_order_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='account_orders', to='account.account'),
            preserve_default=False,
        ),
    ]
