# Generated by Django 5.0 on 2024-01-20 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_is_void_by_user_orderitem_product_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_by_user',
            field=models.ForeignKey(default=935037293335117825, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=935037293335117825),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_void_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_voided_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
