# Generated by Django 5.0 on 2024-01-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_created_by_user_orderitem_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_void_by_user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_by_user',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='updated_date',
        ),
    ]
