# Generated by Django 5.0 on 2024-01-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_orderitem_is_void_by_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='created_date',
        ),
    ]
