# Generated by Django 5.0 on 2024-01-20 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_remove_orderitem_is_void_by_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='created_by_user',
            field=models.ForeignKey(default=935037293335117825, on_delete=django.db.models.deletion.PROTECT, related_name='order_items_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
