# Generated by Django 5.0 on 2024-01-21 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
