# Generated by Django 5.0 on 2024-01-21 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_remove_orderitem_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(default='Milo123456', on_delete=django.db.models.deletion.PROTECT, to='product.product', to_field='sku'),
            preserve_default=False,
        ),
    ]
