# Generated by Django 5.0 on 2024-01-21 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_orderitem_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(db_column='product_sku', on_delete=django.db.models.deletion.PROTECT, to='product.product', to_field='sku'),
        ),
    ]
