# Generated by Django 5.0 on 2024-01-21 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_orderitem_product'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('id', 'product')},
        ),
    ]
