# Generated by Django 5.0 on 2024-01-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_orderitem_unique_together'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
