# Generated by Django 5.0 on 2024-03-07 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_reference_no',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking_info',
        ),
        migrations.AddField(
            model_name='order',
            name='tables',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VOID', 'Void'), ('BILL OUT', 'Bill Out'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
