# Generated by Django 5.0 on 2024-03-12 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_total_vat'),
        ('table', '0004_remove_table_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_table', to='table.table'),
        ),
    ]
