# Generated by Django 5.0 on 2024-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_rename_total_order_total_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_discount',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_total',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_placed',
            field=models.BooleanField(default=False),
        ),
    ]
