# Generated by Django 5.0 on 2024-03-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0025_remove_orderitem_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=set(),
        ),
    ]
