# Generated by Django 5.0 on 2024-03-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='left',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='table',
            name='top',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
