# Generated by Django 5.0 on 2024-03-07 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_remove_order_payment_method_and_more'),
        ('table', '0002_table_left_table_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_order', to='order.order'),
        ),
    ]
