# Generated by Django 5.0 on 2024-03-12 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_table_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='order',
        ),
    ]
